console.log("Jay Ganesh...");
console.log("Om Namah Shivay...");
console.log("Hello World i Am using Typescript..");
console.log("I Love Angular ......");
console.log("     _                      _                 ____ _     ___");
console.log("    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|");
console.log("   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |");
console.log("  / ___  \| | | | (_| | |_| | | (_| | |      | |___| |___ | |");
console.log(" /_/   \_ \_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|");
console.log("                  |___/ ");
